### ISSUE TITLE
 Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by robincajas12** [yasd251/checkbox-sounds-plugin#1]
Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at HTMLDocument.eval (plugin:checkbox-sounds:2274:41)

**Comment by yasd251** [comment]
Hi Robin, 
Thanks for submitting the issue, but may you provide context in which this error is occurring?

**Comment by yasd251** [comment]
Hi, are you still able to provide info as to when this issue is occuring? If not, I will be closing this until further notice. Thanks!
