### ISSUE TITLE
Request: 'Ting' sound effect

### ISSUE THREAD

**Issue by alincoop** [yasd251/checkbox-sounds-plugin#2]
Love your plugin and the 'pop' sound is great, thank you.

Here is my request for a 'ting' sound effect:
https://www.youtube.com/watch?v=uTg0i6j7k34

**Comment by yasd251** [comment]
Hey Alincoop, the sound effect has been added. I am glad you like the plugin!

**Comment by yasd251** [comment]
The new release should be up now, if there are any issues please let me know!

**Comment by alincoop** [comment]
Works great, very satisfying.
