### ISSUE TITLE
Error when used in conjunction with the Tasks plugin.

### ISSUE THREAD

**Issue by OPEN1004MIND** [yasd251/checkbox-sounds-plugin#3]
I know many Obsidian users use the tasks plugin.

The sound is supposed to go off when the checkbox is clicked, but it goes off when the checkbox is unchecked.
It seems to work in reverse because of the tasks plugin.

**Comment by yasd251** [comment]
I see the issue, it seems that the Tasks plugin changes the behavior of the checkboxes when clicked, which interferes with the checks in place to play the sound within this plugin. I will figure a workaround soon and push the update. Thanks for reporting this issue! Will keep you updated

**Comment by yasd251** [comment]
This issue is fixed now, you may update to 1.0.3 for the fixes! Thanks for reporting the issue, do update me to see if it fixes it for you.
