### ISSUE TITLE
No sound when activating the Party plugin 

### ISSUE THREAD

**Issue by OPEN1004MIND** [yasd251/checkbox-sounds-plugin#5]
Thank you for your help with the Tasks plugin issue.
I'd like to let you know about another plugin I'm having trouble with.
It's called Party plugin and when I check the checkbox it shows me what the event looks like, but there's no sound.

**Comment by yasd251** [comment]
Will look into it, thanks for reporting!

**Comment by yasd251** [comment]
Fixed, will up the new release now! (1.0.5) 

Please do inform me if there are any issues with this. Thanks for reporting!
